# Generated by Django 2.2.10 on 2020-09-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.FileField(upload_to=''),
        ),
    ]
