# Generated by Django 2.2.10 on 2020-09-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200902_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.FileField(upload_to='posts_header_image'),
        ),
    ]
