# Generated by Django 3.1.1 on 2020-09-04 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200903_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
